name: Deploy to VPS via Docker

on:
  # Убираем автоматический запуск при пуше в backend
  # push:
  #   branches:
  #     - backend

  # Ставим только ручной запуск
  workflow_dispatch:  # Ручной запуск через GitHub UI
    inputs:
      environment:
        description: 'Choose environment to deploy to'
        required: true
        default: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверяем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Кэшируем слои Docker для ускорения сборки
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # 4. Логинимся в Harbor
      - name: Log in to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login my-harbor.local:8080 -u ${{ secrets.HARBOR_USER }} --password-stdin

      # 5. Строим Docker-образ
      - name: Build Docker image
        run: |
          docker build -t my-harbor.local:8080/nest-backend:${{ github.sha }} .

      # 6. Пушим Docker-образ в Harbor
      - name: Push Docker image to Harbor
        run: |
          docker push my-harbor.local:8080/nest-backend:${{ github.sha }}

      # 7. Устанавливаем sshpass для использования пароля при SSH
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # 8. Деплой на VPS с использованием SSH
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_ROOT_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP }} << 'EOF'
            docker pull my-harbor.local:8080/nest-backend:${{ github.sha }}
            docker stop nest-backend || true
            docker rm nest-backend || true
            docker run -d --name nest-backend -p 3000:3000 my-harbor.local:8080/nest-backend:${{ github.sha }}
          EOF
        env:
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
          VPS_ROOT_PASSWORD: ${{ secrets.VPS_ROOT_PASSWORD }}
          VPS_IP: ${{ secrets.VPS_IP }}

      # 9. Пушим изменения в ветку backend (если есть новые изменения)
      - name: Commit and push changes to backend branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout backend  # Переключаемся на ветку backend
          git add .  # Добавляем все изменения
          git commit -m "Deploy new changes to VPS" || echo "No changes to commit"
          git push origin backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации
