name: Backend Deployment

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Docker to ignore SSL verification
        run: |
          echo '{"insecure-registries": ["tsukawa.ru"]}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          sleep 5

      - name: Log in to Harbor registry
        uses: docker/login-action@v1
        with:
          registry: tsukawa.ru
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
        env:
          DOCKER_CONTENT_TRUST: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

      - name: Build and tag Docker image
        run: |
          docker build -t tsukawa.ru/${{ secrets.HARBOR_PROJECT }}/backend:latest .
          docker tag tsukawa.ru/${{ secrets.HARBOR_PROJECT }}/backend:latest tsukawa.ru/${{ secrets.HARBOR_PROJECT }}/backend:$(date +%Y%m%d%H%M%S)

      - name: Push Docker images
        run: |
          docker push tsukawa.ru/${{ secrets.HARBOR_PROJECT }}/backend:latest
          docker push tsukawa.ru/${{ secrets.HARBOR_PROJECT }}/backend:$(date +%Y%m%d%H%M%S)

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd bot
            echo '{"insecure-registries": ["tsukawa.ru"]}' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
            sleep 5
            docker pull tsukawa.ru/${{ secrets.HARBOR_PROJECT }}/backend:latest
            docker compose up -d --no-deps backend
