name: Backend Deployment

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Harbor registry
        uses: docker/login-action@v2
        with:
          registry: harbor.tsukawa.ru
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harbor.tsukawa.ru/backseezer/backend:latest .
          docker push harbor.tsukawa.ru/backseezer/backend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Создаем рабочую директорию
            mkdir -p ~/backend_seezer
            cd ~/backend_seezer
            
            # Скачиваем актуальный docker-compose.yml
            curl -fsSL "https://raw.githubusercontent.com/O-R-P-H/kursovik-vite-vue/backend/docker-compose.yml" -o docker-compose.yml
            
            # Логинимся в Harbor (если нужно)
            echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.tsukawa.ru -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
            
            # Останавливаем и обновляем контейнеры
            docker compose down || true
            docker compose pull
            docker compose up -d --no-deps main
